### ISSUE TITLE
DEALLOCATE(TMP) erro and MPI-

### ISSUE THREAD

**Issue by joao-ribeiro** [SNL-WaterPower/SNL-SWAN#10]
Hi

I found that de DEALLOCATE(TMP) in line 1220 of SNL-SWAN is give a error when compiling, the workaround for me was: 
IF (ASSOCIATED(TMP)) DEALLOCATE(TMP).

Also, I'm trying to run a large area and for that I need MPI. Those SNL-SWAN work with MPI?

Best regards
João

**Comment by ayomidetobi** [comment]
yes it works with mpi I think this will help
https://github.com/sandialabs/SNL-SWAN/blob/0ce6a5edebf3eda15a1ad821c81af7dae459a60e/src/Makefile#L128

how ever I got same error as you but I tried to go around like you did am still getting same error. what fortran and gcc version are you using

SWAN is preparing computation

At line 1220 of file swanpre1.f
Fortran runtime error: Attempt to DEALLOCATE unallocated 'tmp'

Error termination. Backtrace:
#0  0x7e5823025960 in ???
#1  0x7e58230264d9 in ???
#2  0x7e5823026ad6 in ???
#3  0x6304c57459f5 in swread_
        at /tmp/swan/src/swanpre1.f:1220



this are the new new changes I made in the files
  DEALLOCATE(IARR)                                                40.31
          DEALLOCATE(TMPFT)
          DEALLOCATE(TMPFT)
        IF (ASSOCIATED(TMP)) DEALLOCATE(TMP)                                                   40.31
        IF (ASSOCIATED(TMP)) DEALLOCATE(TMP)                                                   SNL-SWAN
            DEALLOCATE(TMPQ)                                              40.87
        DEALLOCATE(TMPV)
          DEALLOCATE (LAMBDA,CNL4_1,CNL4_2)                               40.17
          DEALLOCATE (RLAMBDA)                                            40.17
      DEALLOCATE(TARR)                                                    40.31
        DEALLOCATE(TARR)                                                  40.31
      DEALLOCATE(XCGRID,YCGRID)                                           40.31
      IF(ALLOCATED(IARR)) DEALLOCATE(IARR)                                40.31
        DEALLOCATE(KGRPNTNEW,SCANND)
